[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/confd/templates` for these files by default
src = "tinc.tmpl"

# The location to place the rendered configuration file
dest = "/etc/tinc/tinc.conf"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys = [ "_coreos.com/fleet/machines/", "_osixia.net/tinc/" ]

# File ownership and mode information
owner = "root"
mode = "0644"

# Reload the actual service once the new config is in place
reload_cmd = "/usr/bin/sv reload tinc"
